
from pyboson.Stream import Stream, noop_callback

class Boson(object):
    def __init__(self, callback=None, resolution=(320,256), device="/dev/video0", framerate=30):
        self.resolution = resolution
        self.framerate  = framerate
        self.device     = device

        # If we had a callback passed in to us then set it up to be called on
        # each frame generated by the Boson, else just pass in the NOOP routine
        # that does nothing for each frame.
        if callback is None:
            self.callback = noop_callback
        else:
            self.callback = callback

        self.stream = Stream(device=device)

    def start(self, pause=0.0):
        self.stream.start(self.callback, pause=pause)

        return True

    def read(self):
        return self.stream.read()

    def stop(self):
        self.stream.stop()

        return True
                    
